### ISSUE TITLE
re-try task that never entered running stage

### ISSUE THREAD

**Issue by keis** [alde/eremetic#11]

**Comment by keis** [comment]
In general I think we want to avoid dealing with retries to keep things simple. However this case is a) tricky to deal with as an api user and b) typically a issue with the cluster and not the application.

**Comment by keis** [comment]
Do you think a more generic re-try concept would be beneficial ?

**Comment by alde** [comment]
Potentially

Do you mean like a POST /task/<id>/retry ?

**Comment by keis** [comment]
not as an api call at that point you could as easily resubmit the original request. Was thinking of something like an attribute to the request ```"retries": 3``` or w/e

**Comment by alde** [comment]
Hmm

I'm a bit torn. Adding generic retries would be pretty much the identical amount of work, but then you must decide (ie document) when those retries will apply since they become part of the public API.

**Comment by keis** [comment]
I'll look into this after #27
