### ISSUE TITLE
Make function parameters immutable

### ISSUE THREAD

**Issue by alde** [alde/eremetic#25]
for example, having

    func createTaskInfo(task *types.EremeticTask, offer *mesos.Offer) *mesos.TaskInfo {
       ...
    }

both modify the "task" variable, and return a TaskInfo is confusing

Better to do

    func createTaskInfo(task *types.EremeticTask, offer *mesos.Offer) (*mesos.TaskInfo, *types.EremeticTask) {
       ...
    }

and return a new EremeticTask struct, and leave the one sent in immutable.

**Comment by keis** [comment]
would be easier to just pass around the task structure by value I guess
